### ISSUE TITLE
Invisible Models when studio_fastpath 1

### ISSUE THREAD

**Issue by ChaoticKamikaze** [mikkokko/csldr#25] opened 2023-07-03 03:45 UTC
certain models become invisible when studio_fastpath is set to : ![img](https://cdn.discordapp.com/attachments/539850572870975488/1125270205132705956/invisblemodels.png)

**Comment by mikkokko** [comment] 2023-07-14 20:59
What map is this?

**Comment by ChaoticKamikaze** [comment] 2023-07-14 21:14
> What map is this?

its the CSO map [Italy EX (aka bzm_italy_mini in the game files)](https://gamebanana.com/mods/448569) but running on CS 1.6

**Comment by mikkokko** [comment] 2023-07-14 21:24
I can't seem to reproduce the issue. What version of the game are you running? Do you have any other client-side addons installed (like MetaHook)?

**Comment by ChaoticKamikaze** [comment] 2023-07-14 21:27
> I can't seem to reproduce the issue. What version of the game are you running? Do you have any other client-side addons installed (like MetaHook)?

Running the steam version of 1.6 No Metahook, just AMXX plugins and ReHLDS (No ReGameDLL though).

**Comment by ChaoticKamikaze** [comment] 2023-07-24 10:59
I think I'm gonna close this. I think what happened has something to do with the specific zombie plague mod I'm using as it has its own optimization code for better performance and I think it conflicts with csldr.

**Comment by mikkokko** [comment] 2023-10-07 11:11
Looks like this was the same issue as #16, fixed in the latest release.

**Closed by mikkokko** 2023-10-07 11:11 UTC
